server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    com.thor: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      logFormat: "%d [%thread] %-5level %logger{36} - %msg%n"

# Default values used by the standard TemplateHealthCheck
template: "Hello, %s!"
defaultName: Stranger

swagger:
  enabled: true
  swaggerVersion: 2.0
  resourcePackage: com.thor.resources
  apiVersion: 1.0.0

rmqConfiguration:
  host: localhost
  port: 5672
  username: guest
  password: guest
  virtualHost: /

actorsConfig: 
  TXN: 
    exchange: txn-exchange
    routingKey: txn-routing-key
    queue: txn-queue
    exchangeType: direct
    durable: true
    autoDelete: false
    arguments: {}
  TXN_REPLY: 
    exchange: txn-exchange
    routingKey: txn-reply-routing-key
    queue: txn-reply-queue
    exchangeType: direct
    durable: true
    autoDelete: false
    arguments: {}
  
    

# Add configuration for RabbitMQ and MQTT connections here later
# rabbitmq:
#   host: localhost
#   port: 5672
#   username: guest
#   password: guest
#   virtualHost: /
# mqtt:
#   brokerUrl: tcp://localhost:1883
#   clientId: dropwizard_publisher
#   username: # optional
#   password: # optional
